### ISSUE TITLE
SqlCache: Add support for concurrency

### ISSUE THREAD

**Issue by ldy985** [LordMike/MBW.Utilities.ManagedSqlite#1]
SqlCache currently uses an unsafe dictionary and causes a crash concurrent workloads.

**Comment by LordMike** [comment]
`SqlCache` shouldn't have been static. It's tightly tied into each instance of the reader (due to the `Sqlite3SchemaRow` as a key).

**Comment by LordMike** [comment]
Ah, it's static because it's an addon information for the parser itself..
