### ISSUE TITLE
Unknown TextEncoding

### ISSUE THREAD

**Issue by ldy985** [LordMike/MBW.Utilities.ManagedSqlite#6]
The parser crashes on a DB where TextEncoding (ReaderBase.cs) is set to 0, the DB can be opened in SQLite browser and PRAGMA encoding returns UTF8.

[1.zip](https://github.com/LordMike/MBW.Utilities.ManagedSqlite/files/3766715/1.zip)

**Comment by LordMike** [comment]
[Docs](https://www.sqlite.org/fileformat2.html#text_encoding) specify that `A value of 1 means UTF-8. A value of 2 means UTF-16le. A value of 3 means UTF-16be. No other values are allowed`.

Where on earth is this file from? :|

Do I need to make a "DefaultEncodingIfNoneSpecified" in the settings? :P
