### ISSUE TITLE
Encoding error on empty databases

### ISSUE THREAD

**Issue by kkriisgaard** [LordMike/MBW.Utilities.ManagedSqlite#8]
Initializing the reader on an empty database causes an `ArgumentOutOfRangeException`, because the encoding is 0.

While there isn't much point in reading an empty database, would it be possible to make a check for emptiness a special case of sorts?

**Comment by LordMike** [comment]
[Corrupt.sqlite.dat.zip](https://github.com/LordMike/MBW.Utilities.ManagedSqlite/files/4914642/Corrupt.sqlite.dat.zip)

**Comment by LordMike** [comment]
Does not seem to be an issue in current code.
